"""No-Node static build. Run from any directory; preserves the original Price Watch content.
SITE_ORIGIN=https://hirethomas.co python3 site-src/static/build.py after verifying domain.
"""
from pathlib import Path
from html import escape
from urllib.parse import quote
import os, re

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
ORIGIN = os.environ.get('SITE_ORIGIN', '').rstrip('/')
def url(path): return ORIGIN + path
def mail(subject): return 'mailto:hello@hirethomas.co?subject=' + quote(subject)
def icon(name):
    paths = {'arrow':'<path d="M7 17 17 7M7 7h10v10"/>', 'file':'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h6"/>', 'chart':'<path d="M3 3v18h18M7 14l4-4 4 3 6-7"/>', 'utensils':'<path d="M4 3v7a2 2 0 0 0 4 0V3M6 3v19M20 3c-4 2-4 8 0 9v10M20 3v9"/>', 'data':'<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5v14a9 3 0 0 0 18 0V5M3 12a9 3 0 0 0 18 0"/>'}
    return '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths[name]+'</svg>'

NAV = [('/obituaries/', 'Obituaries'),('/menus/', 'Menus'),('/agencies/', 'Agencies'),('/pricewatch.html', 'Price Watch'),('/benchmarks/', 'Benchmarks'),('/contact/', 'Contact')]
nav = '<header class="site-header"><div class="wrap nav"><a class="brand" href="'+url('/')+'"><span class="brand-mark">H</span>HireThomas</a><nav aria-label="Main navigation">'+''.join(f'<a href="{url(p)}">{n}</a>' for p,n in NAV)+'</nav></div></header>'
footer = '<footer class="site-footer"><div class="wrap"><div class="footer-links">'+''.join(f'<a href="{url(p)}">{n}</a>' for p,n in NAV)+'</div><p>HireThomas, Inc. · 579 Connecticut Street, San Francisco, CA 94107 · <a href="mailto:hello@hirethomas.co">hello@hirethomas.co</a></p><p class="muted">Operated by AI; a human owner is accountable</p></div></footer>'

def page(title, desc, content, path):
    canonical = f'<link rel="canonical" href="{url(path)}">' if ORIGIN else ''
    theme = path.strip('/') or 'home'
    og = f'<meta property="og:url" content="{url(path)}">' if ORIGIN else ''
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | HireThomas, Inc.</title><meta name="description" content="{escape(desc, quote=True)}">{canonical}{og}<meta property="og:title" content="{escape(title,quote=True)}"><meta property="og:type" content="website"><meta name="theme-color" content="#0f172a"><link rel="icon" href="{url('/favicon.svg')}" type="image/svg+xml"><link rel="preconnect" href="https://rsms.me"><link rel="stylesheet" href="https://rsms.me/inter/inter.css"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,wght@0,400;0,500;0,600;1,400&display=swap" rel="stylesheet"><script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script><link rel="stylesheet" href="{url('/services.css')}"></head><body class="theme-{theme}"><a class="skip" href="#main">Skip to content</a>{nav}<main id="main">{content}</main>{footer}</body></html>'''

def cta(text, subject): return f'<a class="button" href="{mail(subject)}">{text} {icon("arrow")}</a>'
def hero(label, title, intro, action, subject, side):
    return f'<section class="hero"><div class="wrap hero-grid"><div><p class="eyebrow">{label}</p><h1>{title}</h1><p class="intro">{intro}</p>{cta(action,subject)}</div><aside class="offer-card">{side}</aside></div></section>'
def steps(items):
    return '<section class="section tint"><div class="wrap"><p class="eyebrow">Simple by design</p><h2>From your facts to a finished deliverable.</h2><div class="cards three">'+''.join(f'<article class="step"><span class="number">0{i}</span><h3>{t}</h3><p>{s}</p></article>' for i,(t,s) in enumerate(items,1))+'</div></div></section>'
def ordering(items, subject, kicker='Reply-to-order'):
    return '<section class="ordering"><div class="wrap"><div class="ordering-head"><p class="eyebrow">How ordering works</p><a class="ordering-cta" href="'+mail(subject)+'">'+kicker+' '+icon('arrow')+'</a></div><div class="ordering-grid">'+''.join(f'<div class="ordering-step"><span>{i:02d}</span><div><h3>{t}</h3><p>{s}</p></div></div>' for i,(t,s) in enumerate(items,1))+'</div></div></section>'
def contact_band(subject):
    return f'<section class="section"><div class="wrap contact-band"><div><h2>Start with an email.</h2><p>No portal. No sales call. Tell us what you need.</p></div>{cta("Email hello@hirethomas.co",subject)}</div></section>'

obit = hero('For independent funeral homes','Thoughtful obituaries.<br><span>Less time at the keyboard.</span>','Send the family’s facts. Receive a polished obituary within 2 hours, ready for your review and approval before publication.','Try your first two free','Obituary drafting — first two free','<p class="eyebrow">Straightforward pricing</p><div class="price">$40 <small>/ obituary</small></div><p class="highlight">Your first two are free.</p><ul><li>Draft delivered within 2 hours</li><li>Revisions included</li><li>Monthly invoice, payable by ACH or check</li><li>No contract. No minimum.</li></ul>')
obit += '<section class="section"><div class="wrap narrow"><h2>A finished draft, grounded in the facts you send.</h2><p>We turn intake forms, arrangement notes or bullet points into a clear, respectful obituary for your website or the newspaper. Names, dates, relationships and service details are checked against your supplied information. Missing details become questions, not inventions.</p><p>The writing is AI-drafted. Your funeral home and the family review the text and approve it before publication. Please share only information you are authorized to provide and that is needed for the obituary.</p></div></section>'
obit += steps([('Send the family’s facts','Email your intake form, notes or bullet points, plus any length or tone preferences.'),('Receive the draft','We return a polished obituary within 2 hours and revise it using your feedback.'),('Approve, then pay monthly','You approve the final text. The first two are free; subsequent obituaries are $40 each on a monthly ACH/check invoice.')])
obit += ordering([('Reply with the facts','Reply to our email or write hello@hirethomas.co with the authorized family facts and service details.'),('Receive the first draft free','We deliver your first obituary draft within 2 hours, with revisions included.'),('Continue if useful','If you continue, we invoice after delivery, payable by ACH or check to HireThomas, Inc. No contract.')], 'Obituary drafting — first two free')
obit += '''<section class="section"><div class="wrap sample-layout"><div><p class="eyebrow">Sample · entirely fictional</p><h2>A life, told with care.</h2><p>This is a writing demonstration, not client work. The person, family, events and service details are invented.</p></div><article class="sample"><p class="sample-label">Fictional obituary sample</p><h3>Margaret “Peggy” Lindqvist, 1938–2026</h3><p>Margaret Ann Lindqvist, 88, of Cedar Falls, passed away peacefully at home on Tuesday, September 15, 2026, surrounded by her family.</p><p>Peggy was born March 3, 1938, in Waverly to Harold and Ruth (Sorensen) Beck. She graduated from Waverly High School in 1956 and married Carl Lindqvist on June 14, 1958, at St. Paul’s Lutheran Church. Together they farmed north of town for forty years and raised three children.</p><p>A gifted seamstress, Peggy sewed wedding dresses for half the county, and her rhubarb pie took first place at the county fair more years than she cared to admit. She taught Sunday school for three decades, kept a standing Thursday bridge game for fifty years, and never let a grandchild leave the house hungry.</p><p>She is survived by her children, David (Karen) Lindqvist of Ames, Susan (Mark) Whitaker of Cedar Falls, and Thomas Lindqvist of Denver; seven grandchildren; four great-grandchildren; and her sister, Joan Beck of Waverly. She was preceded in death by her husband, Carl, in 2019, and by her parents.</p><p>Funeral services will be held at 10:30 a.m. Saturday at St. Paul’s Lutheran Church, with visitation one hour prior. Memorials may be directed to the church or the Cedar Falls Public Library.</p></article></div></section>'''
obit += contact_band('Obituary drafting — first two free')
obit = obit.replace('Thoughtful obituaries.<br><span>Less time at the keyboard.</span>','Every life deserves<br><span>thoughtful words.</span>')
obit = obit.replace('<p class="sample-label">Fictional obituary sample</p>','<p class="sample-label">A notice of remembrance · fictional sample</p>')

menus = hero('For independent restaurants','Your food deserves<br><span>clearer menu copy.</span>','Every dish. One consistent voice. Appetizing descriptions that stay true to what you actually serve — with Spanish or English translation if you need it.','Request a menu rewrite','Menu rewrite request','<p class="eyebrow">One menu. Fixed price.</p><div class="price">$99 <small>full rewrite</small></div><p class="highlight">$149 with complete Spanish/English translation</p><ul><li>Delivered within 48 hours</li><li>One round of corrections included</li><li>Invoice after delivery</li><li>Pay by ACH or check</li></ul>')
menus += '<section class="section"><div class="wrap narrow"><h2>Ready to paste, publish or send to your printer.</h2><p>You receive a document covering your full menu: every dish rewritten in one voice. Plain text is included; DOCX or PDF is available on request. The $149 option adds a complete Spanish or English translation of the whole menu.</p><p>We use your menu and any facts you confirm. We do not invent ingredients, cooking methods, origins, “house-made” claims or dietary assurances. Copy and translation are AI-drafted and reviewed against your inputs. You approve the final text, including ingredient and allergen accuracy.</p></div></section>'
menus += steps([('Send your menu','Email a menu link or document, anything to keep as-is, and any confirmed details you want emphasized.'),('Receive the rewrite','Within 48 hours, get a full-menu document — plus the complete translation if selected.'),('Review and approve','One round of corrections is included. We invoice after delivery: $99, or $149 with translation, payable by ACH or check.')])
menus += ordering([('Reply with your menu','Reply to our email or write hello@hirethomas.co with your menu, confirmed details and translation preference.'),('Receive the first piece free','We deliver three dish rewrites as your first piece within the stated 48-hour turnaround.'),('Continue if useful','If you continue, we invoice after delivery, payable by ACH or check to HireThomas, Inc. No contract; cancel anytime.')], 'Menu rewrite request')
menus += '''<section class="section"><div class="wrap sample-layout"><div><p class="eyebrow">Fictional menu · sample rewrite</p><h2>More inviting.<br>Nothing made up.</h2><p>This invented dish demonstrates the approach. It is not work for a real restaurant. The rewrite uses only the ingredients and preparation stated in the fictional original.</p></div><article class="sample"><p class="sample-label">Original · fictional</p><h3>Grilled chicken sandwich</h3><p>Grilled chicken, avocado, tomato, lettuce, sourdough. $14</p><hr><p class="sample-label">Sample rewrite</p><p>Grilled chicken layered with avocado, tomato and lettuce on sourdough. $14</p><hr><p class="sample-label">Sample Spanish version</p><p lang="es"><strong>Sándwich de pollo a la parrilla</strong><br>Pollo a la parrilla con aguacate, tomate y lechuga en pan de masa madre. $14</p></article></div></section>'''
menus += contact_band('Menu rewrite request')
menus = menus.replace('<p class="eyebrow">For independent restaurants</p>', '<p class="eyebrow food-label">'+icon('utensils')+' For independent restaurants</p>')
start = menus.index('<article class="sample">')
end = menus.index('</article>',start)+len('</article>')
menus = menus[:start]+'''<article class="sample menu-card"><div class="menu-card-heading"><span>THE SAMPLE MENU</span><span>01</span></div><p class="sample-label">Fictional dish · not client work</p><section class="dish"><p class="sample-label">Before</p><div class="dish-title"><h3>Grilled chicken sandwich</h3><span>$14</span></div><p>Grilled chicken, avocado, tomato, lettuce, sourdough.</p></section><section class="dish"><p class="sample-label">After · sample rewrite</p><div class="dish-title"><h3>Grilled chicken sandwich</h3><span>$14</span></div><p>Grilled chicken layered with avocado, tomato and lettuce on sourdough.</p></section><section class="dish" lang="es"><p class="sample-label">En español · sample translation</p><div class="dish-title"><h3>Sándwich de pollo a la parrilla</h3><span>$14</span></div><p>Pollo a la parrilla con aguacate, tomate y lechuga en pan de masa madre.</p></section><p class="menu-note">Same dish. Clearer words. No added ingredients.</p></article>'''+menus[end:]

agencies = hero('For small marketing & advertising agencies','Your brand.<br><span>Our data work.</span>','Still assembling client reports by hand? No developer time for scrapers? We build and run the public-data collection, then deliver files you can resell under your own brand.','Request your free first deliverable','Agency service — free first deliverable','<p class="eyebrow">Fixed scope, fixed price</p><div class="price">From $49 <small>/ report</small></div><p class="highlight">From $39/month per monitor</p><ul><li>Your first deliverable is free</li><li>Scope and fixed price agreed before work</li><li>White-label CSV and client-ready summaries</li><li>Invoice after delivery</li></ul>')
agencies += '<section class="section"><div class="wrap"><p class="eyebrow">An extra production capability, not another hire</p><h2>Data collection through client-ready reporting.</h2><div class="cards three"><article class="card">'+icon('chart')+'<h3>Competitor & SERP monitoring</h3><p>Track agreed public competitor prices or search-result observations. Receive dated snapshots and change summaries, with source and coverage notes. No promise of rankings or universal coverage.</p></article><article class="card">'+icon('data')+'<h3>Business lead lists</h3><p>Company-level research from public sources: business names, websites, categories and locations in a clean CSV. No personal contact details or personal-data scraping.</p></article><article class="card">'+icon('file')+'<h3>Weekly client reports</h3><p>Turn collected data into a concise weekly summary, with source links, changes and limitations. Use the agreed CSV and report copy under your agency’s brand.</p></article></div></div></section>'
agencies += steps([('Send the brief','Email your sources, fields, client-report format and cadence. We confirm feasibility, scope and a fixed price.'),('Get the first deliverable free','Review an initial report, company list or monitor output. We agree the coverage and format before any paid work.'),('Approve and resell','Approve the deliverable and use it under your brand. Paid reports start at $49; monitors start at $39/month each. We invoice after delivery.')])
agencies += ordering([('Reply with the brief','Reply to our email or write hello@hirethomas.co with the public competitors, sources, fields or report format.'),('Receive the first report free','We deliver your first report or data piece within the stated turnaround after confirming the scope.'),('Continue if useful','If you continue, we invoice after delivery, payable by ACH or check to HireThomas, Inc. No contract; cancel anytime.')], 'Agency service — free first deliverable')
agencies += '<section class="section"><div class="wrap sample-layout"><div><p class="eyebrow">Clear boundaries</p><h2>Public business data.<br>Transparent methods.</h2><p>We use AI for collection tooling, analysis and drafting. White-label delivery does not mean human-only production; it must fit your client’s agreed requirements.</p></div><div class="sample"><h3>What we will not do</h3><ul><li>Scrape personal data or build personal contact lists.</li><li>Collect from login-walled sites.</li><li>Bypass CAPTCHAs or access controls.</li><li>Invent missing data, observations or results.</li></ul><p>We flag unavailable sources and gaps rather than silently replacing them with estimates. Source access and monitoring feasibility are checked before we commit.</p></div></div></section>'
agencies += contact_band('Agency service — free first deliverable')
agency_sample = '''<section class="section report-section"><div class="wrap"><div class="report-heading"><div><p class="eyebrow">Ready for your client workflow</p><h2>Less assembly.<br>More usable reporting.</h2></div><p class="report-note">Sample data (illustrative). Fictional businesses and placeholder observations — not measured results or client work.</p></div><div class="report-panel"><div class="report-toolbar"><strong>Weekly client report</strong><span>SAMPLE DATA (ILLUSTRATIVE)</span></div><div class="table-scroll"><table><thead><tr><th>Monitor</th><th>Source / entity</th><th>Observation</th><th>Report note</th></tr></thead><tbody><tr><td><span class="table-tag">PRICE</span></td><td>Sample Store A</td><td>Price change flagged</td><td>Attach dated source snapshot</td></tr><tr><td><span class="table-tag">SERP</span></td><td>Sample search query</td><td>Result changed</td><td>Include query, locale and collection time</td></tr><tr><td><span class="table-tag">BUSINESS LIST</span></td><td>Sample Company B</td><td>Company record added</td><td>Public website and category only</td></tr><tr><td><span class="table-tag">COVERAGE</span></td><td>Sample Source C</td><td>Source unavailable</td><td>Flag gap; do not invent a value</td></tr></tbody></table></div><div class="report-bottom">Your agreed fields · Source references · Coverage caveats · CSV + summary</div></div><div class="cards two agency-prices"><article class="card"><p class="eyebrow">One-off deliverables</p><h3>From $49 <small>/ report</small></h3><p>A defined brief, agreed output and fixed quote before paid work starts.</p></article><article class="card"><p class="eyebrow">Recurring collection</p><h3>From $39 <small>/ month per monitor</small></h3><p>An agreed source set and cadence. Your first deliverable is free.</p></article></div></div></section>'''
agencies = agencies.replace('<section class="section tint">',agency_sample+'<section class="section tint">',1)

home = '<section class="hero home-hero"><div class="wrap"><p class="eyebrow">Practical services for small businesses</p><h1>Good work.<br><span>Without the extra workload.</span></h1><p class="intro">From thoughtful writing to clean business data, HireThomas turns your brief into a finished deliverable. Clear scope, straightforward pricing, and an email to get started.</p><a class="button" href="'+url('/#services')+'">Find your service '+icon('arrow')+'</a><a class="text-link" href="'+url('/contact/')+'">Talk to us</a></div></section>'
services = [('file','Obituary drafting','For funeral homes','$40 each · first two free','Family facts to a polished obituary in 2 hours. Revisions included; monthly ACH/check invoice.','/obituaries/'),('utensils','Menu copy & translation','For restaurants','$99 · $149 with translation','A full-menu rewrite in 48 hours. One consistent voice; invoice after delivery.','/menus/'),('data','White-label data & reports','For agencies','From $49/report · $39/mo per monitor','Public-data collection, business lists and weekly client reporting. First deliverable free.','/agencies/'),('chart','Competitor Price Watch','For e-commerce','$39/month · $49 one-off','Track product and variant prices at up to 10 competitors. Weekly CSV and a summary of changes.','/pricewatch.html')]
home += '<section class="section" id="services"><div class="wrap"><p class="eyebrow">Choose the work you need off your desk</p><h2>Specialized services. Simple handoffs.</h2><div class="cards two">'+''.join(f'<article class="card">{icon(ic)}<p class="eyebrow">{who}</p><h3><a href="{url(link)}">{name}</a></h3><p class="card-price">{price}</p><p>{desc}</p><a class="service-link" href="{url(link)}">See details {icon("arrow")}</a></article>' for ic,name,who,price,desc,link in services)+'</div></div></section>'
home += '<section class="section tint"><div class="wrap"><h2>Need a focused data or automation job?</h2><div class="cards two"><article class="card"><h3>Web data extraction</h3><p>Clean CSV or JSON from public business data. Starter: $49 for one site, up to 2,000 rows and 10 fields. Standard: $149 for up to 25,000 rows or 3 sites, normalized.</p><p>Free 50-row sample before you commit. Full delivery within 48 hours after approval; methodology note included. Standard includes one free re-run within 7 days.</p>'+cta('Request a data sample','Web data extraction — sample request')+'</article><article class="card"><h3>Scripts & fixes · from $59</h3><p>Small Python or JavaScript scripts, scraper repairs, CSV/Excel transforms and API glue under about 200 lines. Delivered within 24 hours with source code, a short README and one free revision.</p><p>Email the inputs and intended output so we can agree the scope before starting. Data and script work is invoiced after delivery, payable by ACH or wire.</p>'+cta('Describe your task','Scripts and automation request')+'</article></div></div></section>'
home += '<section class="section" id="about"><div class="wrap narrow"><p class="eyebrow">How we work</p><h2>A real company. AI-operated work.</h2><p>HireThomas, Inc. is a Delaware corporation. AI systems perform our drafting, data collection and checks; a human owner is accountable for the business. We work from your supplied facts and permitted public sources, flag uncertainties and put the deliverable in your hands for review.</p></div></section>'
home += '<section class="section tint" id="contact"><div class="wrap contact-band"><div><h2>What can we take off your desk?</h2><p>Email your brief, source material and deadline.</p></div>'+cta('Email hello@hirethomas.co','Service inquiry')+'</div></section>'

contact = hero('Contact HireThomas, Inc.','Tell us what<br><span>you need done.</span>','Email your service request, source material and deadline. We will confirm the scope and next step. You do not need to book a call.','Email hello@hirethomas.co','Service inquiry','<p class="eyebrow">Company contact</p><h2>HireThomas, Inc.</h2><p>579 Connecticut Street<br>San Francisco, CA 94107</p><p><a href="mailto:hello@hirethomas.co">hello@hirethomas.co</a></p><p>Operated by AI; a human owner is accountable</p>')
contact += '<section class="section"><div class="wrap narrow"><h2>What to include</h2><ul><li><strong>Obituaries:</strong> authorized family facts, service details, preferred length and tone.</li><li><strong>Menus:</strong> your current menu and any confirmed details or wording to preserve.</li><li><strong>Agencies:</strong> public source URLs, required fields, report format and frequency.</li><li><strong>Price Watch:</strong> your storefront and the competitors you want to follow.</li></ul><p>Please do not send payment-card details, identity documents, passwords or information you do not have permission to share. Bank payment instructions appear on company invoices, not on this website.</p></div></section>'

pages = {'index.html':page('Writing, data & reporting for small businesses','Fixed-price obituary drafting, menu rewrites, agency data services and competitor price monitoring.',home,'/'), 'obituaries/index.html':page('Obituary drafting for funeral homes','$40 per obituary; first two free. Draft in 2 hours, revisions included, monthly ACH/check invoice.',obit,'/obituaries/'), 'menus/index.html':page('Menu rewriting & Spanish/English translation','$99 full-menu rewrite or $149 with translation. Delivered in 48 hours; invoice after delivery.',menus,'/menus/'), 'agencies/index.html':page('White-label data & reporting for agencies','Public-data collection, business lists and weekly reports. From $49/report or $39/month per monitor; first deliverable free.',agencies,'/agencies/'), 'contact/index.html':page('Contact','Email hello@hirethomas.co to start a service request.',contact,'/contact/')}
# Keep the existing Price Watch offer and examples intact; replace only the common shell and contact identity.
legacy = (HERE/'pricewatch-original.html').read_text()
legacy = re.sub(r'<header\b.*?</header>',nav,legacy,flags=re.S)
legacy = re.sub(r'<footer\b.*?</footer>',footer,legacy,flags=re.S)
legacy = legacy.replace('hirethomas.inc@proton.me','hello@hirethomas.co')
legacy = legacy.replace('https://hirethomas-inc.github.io',ORIGIN or '')
legacy = re.sub(r'href="/pricewatch(?:\.html)?"',f'href="{url("/pricewatch.html")}"',legacy)
legacy = legacy.replace('href="/#quote"',f'href="{url("/contact/")}"').replace('href="/#process"',f'href="{url("/contact/")}"').replace('href="/#faq"',f'href="{url("/contact/")}"')
legacy = legacy.replace('</head>',f'<link rel="stylesheet" href="{url("/services.css")}"></head>')
if ORIGIN:
    legacy = re.sub(r'(href|src)="(/(?!/)[^"]*)"',lambda m:m[1]+'="'+url(m[2])+'"',legacy)
    legacy = legacy.replace(url('/pricewatch')+'"',url('/pricewatch.html')+'"')
pages['pricewatch.html'] = legacy

# Secondary card-payment options; preserve invoice ordering.
card_blocks = {'pricewatch.html': '<div class="card-payment-options" style="margin-top:1.5rem"><p style="margin:0.5rem 0">Weekly report · $39/mo — <a style="text-decoration:underline" href="https://buy.stripe.com/9B614p5HL0dacoGfNl6g807">Pay by card (Stripe)</a></p><p style="margin:0.5rem 0">One-off benchmark · $49 — <a style="text-decoration:underline" href="https://buy.stripe.com/8x2dRb9Y15xu1K29oX6g806">Pay by card (Stripe)</a></p><p style="font-size:0.875rem;margin-top:0.75rem">Invoice after delivery (ACH/check) remains available; for monthly plans we send the card link after you accept the free first report.</p></div>', 'obituaries/index.html': '<div class="card-payment-options" style="margin-top:1.5rem"><p style="margin:0.5rem 0">Per obituary · $40 — <a style="text-decoration:underline" href="https://buy.stripe.com/5kQ8wR4DH3pmcoGfNl6g808">Pay by card (Stripe)</a></p><p style="font-size:0.875rem;margin-top:0.75rem">Invoice after delivery (ACH/check) remains available; for monthly plans we send the card link after you accept the free first report.</p></div>', 'menus/index.html': '<div class="card-payment-options" style="margin-top:1.5rem"><p style="margin:0.5rem 0">Full menu · $99 — <a style="text-decoration:underline" href="https://buy.stripe.com/4gMeVfeeh7FC3SacB96g809">Pay by card (Stripe)</a></p><p style="margin:0.5rem 0">With translation · $149 — <a style="text-decoration:underline" href="https://buy.stripe.com/14AdRb3zD4tq60i8kT6g80a">Pay by card (Stripe)</a></p><p style="font-size:0.875rem;margin-top:0.75rem">Invoice after delivery (ACH/check) remains available; for monthly plans we send the card link after you accept the free first report.</p></div>', 'agencies/index.html': '<div class="card-payment-options" style="margin-top:1.5rem"><p style="margin:0.5rem 0">Per report · $49 — <a style="text-decoration:underline" href="https://buy.stripe.com/5kQcN74DH5xudsKbx56g80b">Pay by card (Stripe)</a></p><p style="margin:0.5rem 0">Per monitor · $39/mo — <a style="text-decoration:underline" href="https://buy.stripe.com/4gM8wRdad3pmdsK0Sr6g80c">Pay by card (Stripe)</a></p><p style="font-size:0.875rem;margin-top:0.75rem">Invoice after delivery (ACH/check) remains available; for monthly plans we send the card link after you accept the free first report.</p></div>'}
for card_name, card_block in card_blocks.items():
    card_html = pages[card_name]
    if card_name == "pricewatch.html":
        card_marker = "$39/month · cancel anytime · or a one-off benchmark for $49</p>"
        card_html = card_html.replace(card_marker, card_marker + card_block)
    else:
        card_start = card_html.index('<section class="ordering">')
        card_end = card_html.index("</section>", card_start)
        card_html = card_html[:card_end-6] + card_block + card_html[card_end-6:]
    pages[card_name] = card_html

for name, text in pages.items():
    text = text.replace('<br><span>', '<br> <span>')
    text = text.replace('/services.css"', '/services.css?v=20260927b"')
    if ORIGIN: text = re.sub(r'href="#([^" ]*)"',lambda m:'href="'+url('/' if name=='index.html' else ('/pricewatch.html' if name=='pricewatch.html' else '/'+name.split('/')[0]+'/'))+'#'+m[1]+'"',text)
    p = ROOT/name
    p.parent.mkdir(parents=True,exist_ok=True)
    p.write_text(text)
    print(name, len(text))
(ROOT/'services.css').write_text((HERE/'services.css').read_text())

# Public benchmark pages (/benchmarks/...). Data: site-src/data/benchmarks/*.json (anonymized); see benchmarks.py.
import sys
sys.path.insert(0, str(HERE))
import benchmarks
benchmarks.render(nav, footer, url, ROOT)
